import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

const routes: Routes = [
    { path: '', redirectTo: 'chart', pathMatch: 'full' },
    { path: 'chart', loadChildren: './pages/chart/chart.module#ChartPageModule' },
    { path: 'advanced-data-labelling', loadChildren: './pages/advanced-data-labelling/advanced-data-labelling.module#AdvancedDataLabellingPageModule' },
    { path: 'advanced-progress-bar', loadChildren: './pages/advanced-progress-bar/advanced-progress-bar.module#AdvancedProgressBarPageModule' },
    { path: 'legend-positioning', loadChildren: './pages/legend-positioning/legend-positioning.module#LegendPositioningPageModule' },
    { path: 'legend-point-style', loadChildren: './pages/legend-point-style/legend-point-style.module#LegendPointStylePageModule' },
    { path: 'charts-radar', loadChildren: './pages/charts-radar/charts-radar.module#ChartsRadarPageModule' },
    { path: 'charts-combo-bar-line', loadChildren: './pages/charts-combo-bar-line/charts-combo-bar-line.module#ChartsComboBarLinePageModule' },
    { path: 'charts-polar-area', loadChildren: './pages/charts-polar-area/charts-polar-area.module#ChartsPolarAreaPageModule' },
    { path: 'charts-pie', loadChildren: './pages/charts-pie/charts-pie.module#ChartsPiePageModule' },
    { path: 'charts-area-line-datasets', loadChildren: './pages/charts-area-line-datasets/charts-area-line-datasets.module#ChartsAreaLineDatasetsPageModule' },
    { path: 'charts-area-radar', loadChildren: './pages/charts-area-radar/charts-area-radar.module#ChartsAreaRadarPageModule' },
    { path: 'charts-area-line-stacked', loadChildren: './pages/charts-area-line-stacked/charts-area-line-stacked.module#ChartsAreaLineStackedPageModule' },
    { path: 'charts-area-line-boundaries', loadChildren: './pages/charts-area-line-boundaries/charts-area-line-boundaries.module#ChartsAreaLineBoundariesPageModule' },
    { path: 'charts-bubble', loadChildren: './pages/charts-bubble/charts-bubble.module#ChartsBubblePageModule' },
    { path: 'charts-radar-skip-points', loadChildren: './pages/charts-radar-skip-points/charts-radar-skip-points.module#ChartsRadarSkipPointsPageModule' },
    { path: 'charts-scatter-basic', loadChildren: './pages/charts-scatter-basic/charts-scatter-basic.module#ChartsScatterBasicPageModule' },
    { path: 'charts-scatter-multi-axis', loadChildren: './pages/charts-scatter-multi-axis/charts-scatter-multi-axis.module#ChartsScatterMultiAxisPageModule' },
    { path: 'charts-line-basic', loadChildren: './pages/charts-line-basic/charts-line-basic.module#ChartsLineBasicPageModule' },
    { path: 'charts-line-point-sizes', loadChildren: './pages/charts-line-point-sizes/charts-line-point-sizes.module#ChartsLinePointSizesPageModule' },
    { path: 'charts-line-multi-axis', loadChildren: './pages/charts-line-multi-axis/charts-line-multi-axis.module#ChartsLineMultiAxisPageModule' },
    { path: 'charts-line-stepped', loadChildren: './pages/charts-line-stepped/charts-line-stepped.module#ChartsLineSteppedPageModule' },
    { path: 'charts-line-skip-points', loadChildren: './pages/charts-line-skip-points/charts-line-skip-points.module#ChartsLineSkipPointsPageModule' },
    { path: 'charts-line-point-styles', loadChildren: './pages/charts-line-point-styles/charts-line-point-styles.module#ChartsLinePointStylesPageModule' },
    { path: 'charts-line-line-styles', loadChildren: './pages/charts-line-line-styles/charts-line-line-styles.module#ChartsLineLineStylesPageModule' },
    { path: 'charts-line-interpolation-modes', loadChildren: './pages/charts-line-interpolation-modes/charts-line-interpolation-modes.module#ChartsLineInterpolationModesPageModule' },
    { path: 'charts-bar-vertical', loadChildren: './pages/charts-bar-vertical/charts-bar-vertical.module#ChartsBarVerticalPageModule' },
    { path: 'charts-bar-horizontal', loadChildren: './pages/charts-bar-horizontal/charts-bar-horizontal.module#ChartsBarHorizontalPageModule' },
    { path: 'charts-bar-stacked', loadChildren: './pages/charts-bar-stacked/charts-bar-stacked.module#ChartsBarStackedPageModule' },
    { path: 'charts-bar-multi-axis', loadChildren: './pages/charts-bar-multi-axis/charts-bar-multi-axis.module#ChartsBarMultiAxisPageModule' },
    { path: 'charts-bar-stacked-group', loadChildren: './pages/charts-bar-stacked-group/charts-bar-stacked-group.module#ChartsBarStackedGroupPageModule' },
    { path: 'charts-doughnut', loadChildren: './pages/charts-doughnut/charts-doughnut.module#ChartsDoughnutPageModule' },
    { path: 'scales-toggle-scale-type', loadChildren: './pages/scales-toggle-scale-type/scales-toggle-scale-type.module#ScalesToggleScaleTypePageModule' },
    { path: 'scales-non-numeric-y', loadChildren: './pages/scales-non-numeric-y/scales-non-numeric-y.module#ScalesNonNumericYPageModule' },
    { path: 'scales-gridlines-display', loadChildren: './pages/scales-gridlines-display/scales-gridlines-display.module#ScalesGridlinesDisplayPageModule' },
    { path: 'scales-linear-min-max-suggested', loadChildren: './pages/scales-linear-min-max-suggested/scales-linear-min-max-suggested.module#ScalesLinearMinMaxSuggestedPageModule' },
    { path: 'scales-linear-step-size', loadChildren: './pages/scales-linear-step-size/scales-linear-step-size.module#ScalesLinearStepSizePageModule' },
    { path: 'scales-linear-min-max', loadChildren: './pages/scales-linear-min-max/scales-linear-min-max.module#ScalesLinearMinMaxPageModule' },
    { path: 'scales-logarithmic-scatter', loadChildren: './pages/scales-logarithmic-scatter/scales-logarithmic-scatter.module#ScalesLogarithmicScatterPageModule' },
    { path: 'scales-logarithmic-line', loadChildren: './pages/scales-logarithmic-line/scales-logarithmic-line.module#ScalesLogarithmicLinePageModule' },
    { path: 'scales-multiline-labels', loadChildren: './pages/scales-multiline-labels/scales-multiline-labels.module#ScalesMultilineLabelsPageModule' },
    { path: 'scales-time-combo', loadChildren: './pages/scales-time-combo/scales-time-combo.module#ScalesTimeComboPageModule' },
    { path: 'scales-time-line-point-data', loadChildren: './pages/scales-time-line-point-data/scales-time-line-point-data.module#ScalesTimeLinePointDataPageModule' },
    { path: 'scales-time-financial', loadChildren: './pages/scales-time-financial/scales-time-financial.module#ScalesTimeFinancialPageModule' },
    { path: 'scales-time-line', loadChildren: './pages/scales-time-line/scales-time-line.module#ScalesTimeLinePageModule' },
    { path: 'scales-gridlines-style', loadChildren: './pages/scales-gridlines-style/scales-gridlines-style.module#ScalesGridlinesStylePageModule' },
    { path: 'scales-filtering-labels', loadChildren: './pages/scales-filtering-labels/scales-filtering-labels.module#ScalesFilteringLabelsPageModule' },
    { path: 'scriptable-bubble', loadChildren: './pages/scriptable-bubble/scriptable-bubble.module#ScriptableBubblePageModule' },
    { path: 'scriptable-bar', loadChildren: './pages/scriptable-bar/scriptable-bar.module#ScriptableBarPageModule' },
    { path: 'tooltips-callbacks', loadChildren: './pages/tooltips-callbacks/tooltips-callbacks.module#TooltipsCallbacksPageModule' },
    { path: 'tooltips-custom-points', loadChildren: './pages/tooltips-custom-points/tooltips-custom-points.module#TooltipsCustomPointsPageModule' },
    { path: 'tooltips-border', loadChildren: './pages/tooltips-border/tooltips-border.module#TooltipsBorderPageModule' },
    { path: 'tooltips-positioning', loadChildren: './pages/tooltips-positioning/tooltips-positioning.module#TooltipsPositioningPageModule' },
    { path: 'tooltips-custom-line', loadChildren: './pages/tooltips-custom-line/tooltips-custom-line.module#TooltipsCustomLinePageModule' },
    { path: 'tooltips-interactions', loadChildren: './pages/tooltips-interactions/tooltips-interactions.module#TooltipsInteractionsPageModule' },
    { path: 'tooltips-custom-pie', loadChildren: './pages/tooltips-custom-pie/tooltips-custom-pie.module#TooltipsCustomPiePageModule' },
];

@NgModule({
    imports: [RouterModule.forRoot(routes)],
    exports: [RouterModule]
})
export class AppRoutingModule { }
